name: docking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pillow
  - pyyaml
  - seaborn
  - biopython
  - openbabel
  - pip
  - pip:
      - openbabel-wheel
      - plip
      - py3Dmol
      - tqdm


