# ───── Docking mode ─────
#  full_matrix     – every ligand vs every receptor
#  diagonal        – only matching rows in complexes.csv (R_i ↔ L_i)
#  redock_native   – only native ligands (validation)
docking_mode: full_matrix


ligand_csv:
  enabled: true  # set true when you have a CSV with test ligands (full_matrix/diagonal modes)
  file: "data/ligands/ligands.csv"
  smiles_column: "SMILES"
  id_column: "ID"


paths:
  receptors_folder: "data/receptors"
  receptors_cleaned_folder: "data/receptors_cleaned"
  native_ligands_folder: "data/native_ligands"
  ligands_folder: "data/ligands"
  output_folder: "results"
  crystals_folder: "data/crystals"
  temp_dir: "tmp"
  smina_path: "/usr/local/bin/smina"
  visuals: "results/visuals"


runtime:
  pool_size: 6        # number of parallel docking workers
  cpu_per_job: 1      # threads per Smina process (give each worker its own core)


# Docking parameters for Smina
# Structure: 'default' applies to full_matrix and diagonal modes.
#            'redock_native' overrides default values when docking_mode = redock_native
docking_params:
  # Base parameters (used for full_matrix and diagonal modes)
  default:
    num_modes: 10          # Number of binding poses to generate (standard value)
    exhaustiveness: 16     # Search thoroughness (higher = slower but more accurate)
    autobox_add: 1         # Grid box padding around ligand (Angstroms)

  # Overrides for native redocking (validation mode)
  # These values are merged with 'default' when docking_mode = redock_native
  redock_native:
    num_modes: 10          # More poses needed to select best RMSD match
    exhaustiveness: 16    # Same as default
    autobox_add: 4        # Larger box for flexible native ligands



fetch_crystals:
  enabled: true
  pdb_ids: ['1M17','4I23','8GUA','4EKL','5OQ4','4LMN','5HD4','6SCM','5EHR','4L7B','5L2S','5L2I','5L2T']  # PDB IDs of the crystal native structures

  ligand_resnames:                                   # Ligand resnames of the protein crystal structures
    1M17: 'AQ4'
    4I23: '1C9'
    8GUA: '1LT'
    4EKL: '0RF'
    5OQ4: 'A3W'
    4LMN: 'EUI'
    5HD4: '38Z'
    6SCM: 'L7H'
    5EHR: '5OD'
    4L7B: '1VV'
    5L2S: '6ZV'
    5L2I: 'LQQ'
    5L2T: '6ZZ'


postprocess:
  native_margin: 0.5
  top_n: 20



