# ───── Docking mode ─────
#  full_matrix     – every ligand vs every receptor
#  diagonal        – only matching rows in complexes.csv (R_i ↔ L_i)
#  redock_native   – only native ligands (validation)
docking_mode: full_matrix


ligand_csv:
  enabled: true  # set true when you have a CSV with test ligands (full_matrix/diagonal modes)
  file: "data/ligands/ligands.csv"
  smiles_column: "SMILES"
  id_column: "ID"


paths:
  receptors_folder: "data/receptors"
  receptors_cleaned_folder: "data/receptors_cleaned"
  native_ligands_folder: "data/native_ligands"
  ligands_folder: "data/ligands"
  output_folder: "results"
  crystals_folder: "data/crystals"
  temp_dir: "tmp"
  smina_path: "/usr/local/bin/smina"
  visuals: "results/visuals"


runtime:
  pool_size: 6        # number of parallel docking workers
  cpu_per_job: 1      # threads per Smina process (give each worker its own core)


# global defaults (can be overridden per‑receptor by gridbox_generator)
docking_params:
  default:
    num_modes: 6
    exhaustiveness: 16
    autobox_add: 1

  redock_native:
    num_modes: 12           # generate multiple poses so RMSD can pick the best
    exhaustiveness: 16      # deeper search to avoid getting stuck in local minima
    autobox_add: 4          # slightly larger search box for flexible ligands



fetch_crystals:
  enabled: true
  pdb_ids: ['1M17','4I23','8GUA','4EKL','5OQ4','4LMN','5HD4','6SCM','5EHR','4L7B','5L2S','5L2I','5L2T']  # PDB IDs of the crystal native structures

  ligand_resnames:                                   # Ligand resnames of the protein crystal structures
    1M17: 'AQ4'
    4I23: '1C9'
    8GUA: '1LT'
    4EKL: '0RF'
    5OQ4: 'A3W'
    4LMN: 'EUI'
    5HD4: '38Z'
    6SCM: 'L7H'
    5EHR: '5OD'
    4L7B: '1VV'
    5L2S: '6ZV'
    5L2I: 'LQQ'
    5L2T: '6ZZ'


postprocess:
  native_margin: 0.5
  top_n: 20



